packages:
  - "packages/*"
  - "services/*"
  - "apps/*"

allowBuilds:
  esbuild: true
  keccak: true
  bufferutil: true
  utf-8-validate: true
  workerd: true

minimumReleaseAgeExclude:
  - '@x402/core@2.27.0'
  - '@x402/evm@2.27.0'
  - '@x402/svm@2.27.0'
