// Generated by scripts/bundle-receipts.mjs. Do not edit.
// Source of truth is evidence/executions/ at the repo root.
import type {StoredReceipt} from "./receipts";

export const BUNDLED_RECEIPTS: Record<string, StoredReceipt> = {
  "0x35f6be3f799207251c42673d6826dc837b30813a8ad257076c61c112c99256f4": {
  "receiptVersion": "1.0",
  "orderId": "0xa6a4cd9d64a11b0c1d8b6b6cc71cc838caa75a6ec726a1d1fccb7b468b403c2a",
  "occurrenceIndex": 0,
  "recurringId": null,
  "owner": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "vault": "0x225885C2eA154Ec53e5E8f768Ad6590Fb9dd13e5",
  "receiver": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "assetId": "0x6977a0680ac0652ec999cfcedf22b8c77022895b68a44c7a0e8854e30cbfdd44",
  "assetSymbol": "NVDAx",
  "assetRegistryRevisionAtCreation": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "assetRegistryRevisionAtExecution": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "underlyingAddress": "0xc845b2894dBddd03858fd2D643B4eF725fE0849d",
  "wrapperAddress": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
  "wrapperVersion": 2,
  "deliveredInstrument": "wrapped",
  "inputToken": "0x4ae46a509F6b1D9056937BA4500cb143933D2dc8",
  "inputTokenSymbol": "USDG",
  "triggerType": "IMMEDIATE",
  "conditionIntent": "immediate",
  "conditionSource": "none (immediate)",
  "conditionSourceTier": "NONE",
  "conditionSourceVersion": "v2",
  "conditionObservationTimestamp": null,
  "conditionObservationHash": null,
  "conditionSourcePayloadHash": null,
  "marketStatus": "n/a",
  "corporateActionState": "none pending",
  "amountReserved": "1000000",
  "actualInputSpent": "1000000",
  "unusedInputReleased": "0",
  "actualOutputReceived": "4436098998761848",
  "minimumOutput": "4402828256271134",
  "quoteSource": "Uniswap v3 pool, quoted on chain via QuoterV2",
  "quoteTimestamp": "2026-09-25T20:45:40.000Z",
  "quoteHash": null,
  "routeSummary": "Uniswap v3 SwapRouter02 0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA, single pool",
  "routerAddress": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "approvalTarget": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "executionPrice": null,
  "observedDifferenceBps": null,
  "executionRequestedAt": "2026-09-25T20:45:43.707Z",
  "transactionSubmittedAt": "2026-09-25T20:45:51.886Z",
  "transactionHash": "0x8c07cfb0776be79a6908c94a76c0c67c766b518d5b6572772b64fec0d5b32427",
  "blockNumber": "71600116",
  "blockHash": "0x372e0402d8e1500e41cfad7593e591ed230d85136ce9d4bb2903700bb93ce1b5",
  "verificationSource": "https://xlayerrpc.okx.com",
  "broadcastSource": "https://rpc.xlayer.tech",
  "firstVerificationAt": "2026-09-25T20:45:53.645Z",
  "finalVerificationAt": "2026-09-25T20:45:58.779Z",
  "verificationPolicy": "3 confirmations, independent RPC readback",
  "confirmations": 2,
  "verificationChecks": [
    {
      "name": "transaction status",
      "passed": true,
      "expected": "success",
      "observed": "success"
    },
    {
      "name": "order terminal state",
      "passed": true,
      "expected": "FILLED",
      "observed": "FILLED"
    },
    {
      "name": "receiver unchanged from intent",
      "passed": true,
      "expected": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
      "observed": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088"
    },
    {
      "name": "executed exactly once",
      "passed": true,
      "expected": "1",
      "observed": "1"
    },
    {
      "name": "output asset is the registered asset",
      "passed": true,
      "expected": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
      "observed": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5"
    },
    {
      "name": "input actually spent",
      "passed": true,
      "expected": "> 0",
      "observed": "1000000"
    },
    {
      "name": "spend within reservation",
      "passed": true,
      "expected": "<= 1000000",
      "observed": "1000000"
    },
    {
      "name": "output meets the user's minimum",
      "passed": true,
      "expected": ">= 0",
      "observed": "4436098998761848"
    },
    {
      "name": "receiver balance increased by the reported output",
      "passed": true,
      "expected": ">= 4436098998761848",
      "observed": "4436098998761848"
    },
    {
      "name": "vault input decreased by exactly the reported spend",
      "passed": true,
      "expected": "1000000",
      "observed": "1000000"
    },
    {
      "name": "reservation fully settled",
      "passed": true,
      "expected": "closed, 0 remaining",
      "observed": "active=false remaining=0"
    }
  ],
  "finalOutcomeStatus": "PARTIALLY_VERIFIED",
  "limitations": [
    "Market session was established from the xStocks issuer's published trading state and signed by the Bespeak operator. It is operator-attested, not oracle-verified. The signature proves which key asserted this state and when; it does not prove the state itself was correct."
  ],
  "receiptId": "0x35f6be3f799207251c42673d6826dc837b30813a8ad257076c61c112c99256f4"
} as unknown as StoredReceipt,
  "0x44072be5faf20526ef5700d516a01571159eb2e1748f0e0f12348e9bdc2c2337": {
  "receiptVersion": "1.0",
  "orderId": "0xf51d7bd508921d5ecd10036f2465273d86869d901265c7d0dd64ad291828f9a6",
  "occurrenceIndex": 0,
  "recurringId": null,
  "owner": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "vault": "0x225885C2eA154Ec53e5E8f768Ad6590Fb9dd13e5",
  "receiver": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "assetId": "0x6977a0680ac0652ec999cfcedf22b8c77022895b68a44c7a0e8854e30cbfdd44",
  "assetSymbol": "NVDAx",
  "assetRegistryRevisionAtCreation": "0x0",
  "assetRegistryRevisionAtExecution": "0x0",
  "underlyingAddress": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
  "wrapperAddress": null,
  "wrapperVersion": 2,
  "deliveredInstrument": "wrapped",
  "inputToken": "0x4ae46a509F6b1D9056937BA4500cb143933D2dc8",
  "inputTokenSymbol": "",
  "triggerType": "NEXT_REGULAR_SESSION",
  "conditionIntent": "underlying US equity in its regular trading session",
  "conditionSource": "xstocks.fi/api/v2/public/assets",
  "conditionSourceTier": "ATTESTED_SESSION",
  "conditionSourceVersion": "v2",
  "conditionObservationTimestamp": "2026-09-25T19:54:14.000Z",
  "conditionObservationHash": null,
  "conditionSourcePayloadHash": "0x443456b53a1c991ce9c7b49606400ac6e68eb3ea00491d4383d3947bd28f9df6",
  "marketStatus": "market",
  "corporateActionState": "none pending",
  "amountReserved": "1000000",
  "actualInputSpent": "0",
  "unusedInputReleased": "0",
  "actualOutputReceived": "0",
  "minimumOutput": "4409654702323366",
  "quoteSource": "OKX DEX aggregator v6",
  "quoteTimestamp": "2026-09-25T19:54:24.000Z",
  "quoteHash": null,
  "routeSummary": "OKX DEX router 0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "routerAddress": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "approvalTarget": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "executionPrice": null,
  "observedDifferenceBps": null,
  "executionRequestedAt": "2026-09-25T19:54:27.539Z",
  "transactionSubmittedAt": "2026-09-25T19:54:34.157Z",
  "transactionHash": "0xea4b71834b9b5fc30e022281049d9ce82ea3adddcbdcc3ac521fd15064fb2016",
  "blockNumber": "71597038",
  "blockHash": "0x890a316b1d9802e4b9cc1e3cdb9bb2824d8a352ecd963c9ccd3335d0e5f65f36",
  "verificationSource": "https://xlayerrpc.okx.com",
  "broadcastSource": "https://rpc.xlayer.tech",
  "firstVerificationAt": "2026-09-25T19:54:35.628Z",
  "finalVerificationAt": "2026-09-25T19:54:42.220Z",
  "verificationPolicy": "3 confirmations, independent RPC readback",
  "confirmations": 3,
  "verificationChecks": [
    {
      "name": "transaction status",
      "passed": true,
      "expected": "success",
      "observed": "success"
    },
    {
      "name": "order terminal state",
      "passed": true,
      "expected": "FILLED",
      "observed": "FILLED"
    },
    {
      "name": "receiver unchanged from intent",
      "passed": true,
      "expected": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
      "observed": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088"
    },
    {
      "name": "executed exactly once",
      "passed": true,
      "expected": "1",
      "observed": "1"
    },
    {
      "name": "output asset is the registered asset",
      "passed": true,
      "expected": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
      "observed": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5"
    },
    {
      "name": "input actually spent",
      "passed": true,
      "expected": "> 0",
      "observed": "1000000"
    },
    {
      "name": "spend within reservation",
      "passed": true,
      "expected": "<= 1000000",
      "observed": "1000000"
    },
    {
      "name": "output meets the user's minimum",
      "passed": true,
      "expected": ">= 0",
      "observed": "4442977030048732"
    },
    {
      "name": "receiver balance increased by the reported output",
      "passed": true,
      "expected": ">= 4442977030048732",
      "observed": "4442977030048732"
    },
    {
      "name": "vault input decreased by exactly the reported spend",
      "passed": true,
      "expected": "1000000",
      "observed": "1000000"
    },
    {
      "name": "reservation fully settled",
      "passed": true,
      "expected": "closed, 0 remaining",
      "observed": "active=false remaining=0"
    }
  ],
  "finalOutcomeStatus": "VERIFIED_FILLED",
  "limitations": [
    "Market session was established from the xStocks issuer's published trading state and signed by the Bespeak operator. It is operator-attested, not oracle-verified. The signature proves which key asserted this state and when; it does not prove the state itself was correct.",
    "Session was read as \"market\" for NVDAx at 2026-09-25T19:54:14.000Z and is claimed only for that observation."
  ],
  "receiptId": "0x44072be5faf20526ef5700d516a01571159eb2e1748f0e0f12348e9bdc2c2337"
} as unknown as StoredReceipt,
  "0x78e041e7c48abb86543eec793de7608a6f79303e25f1e1293f0bd8c4c7221b8d": {
  "receiptVersion": "1.0",
  "orderId": "0x302c7b0f8ef7841e63fa083b0cbf6804e4864bcadbfdd3a5ae49a438143c1c9b",
  "occurrenceIndex": 0,
  "recurringId": null,
  "owner": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "vault": "0x225885C2eA154Ec53e5E8f768Ad6590Fb9dd13e5",
  "receiver": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "assetId": "0x6977a0680ac0652ec999cfcedf22b8c77022895b68a44c7a0e8854e30cbfdd44",
  "assetSymbol": "NVDAx",
  "assetRegistryRevisionAtCreation": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "assetRegistryRevisionAtExecution": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "underlyingAddress": "0xc845b2894dBddd03858fd2D643B4eF725fE0849d",
  "wrapperAddress": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
  "wrapperVersion": 2,
  "deliveredInstrument": "wrapped",
  "inputToken": "0x4ae46a509F6b1D9056937BA4500cb143933D2dc8",
  "inputTokenSymbol": "USDG",
  "triggerType": "IMMEDIATE",
  "conditionIntent": "immediate",
  "conditionSource": "none (immediate)",
  "conditionSourceTier": "NONE",
  "conditionSourceVersion": "v2",
  "conditionObservationTimestamp": null,
  "conditionObservationHash": null,
  "conditionSourcePayloadHash": null,
  "marketStatus": "n/a",
  "corporateActionState": "none pending",
  "amountReserved": "40000",
  "actualInputSpent": "40000",
  "unusedInputReleased": "0",
  "actualOutputReceived": "178247452766875",
  "minimumOutput": "178234084207917",
  "quoteSource": "OKX DEX aggregator v6",
  "quoteTimestamp": "2026-09-25T21:18:28.000Z",
  "quoteHash": null,
  "routeSummary": "OKX DEX router 0x7c5bEE2a8091C3ef39072f64F18Fac913060AEaF",
  "routerAddress": "0x7c5bEE2a8091C3ef39072f64F18Fac913060AEaF",
  "approvalTarget": "0x8b773D83bc66Be128c60e07E17C8901f7a64F000",
  "executionPrice": null,
  "observedDifferenceBps": null,
  "executionRequestedAt": "2026-09-25T21:18:31.563Z",
  "transactionSubmittedAt": "2026-09-25T21:18:38.486Z",
  "transactionHash": "0x72be50dc257b24c0fdc06c421f94c20f1cd0d4fa2d2da86147d8ddbdc8f92e07",
  "blockNumber": "71602083",
  "blockHash": "0x09e752f81d6d90883b05ab2a9a30765538bb73d85f1975339dcdf926ad1d75bf",
  "verificationSource": "https://xlayerrpc.okx.com",
  "broadcastSource": "https://rpc.xlayer.tech",
  "firstVerificationAt": "2026-09-25T21:18:42.946Z",
  "finalVerificationAt": "2026-09-25T21:18:48.568Z",
  "verificationPolicy": "3 confirmations, independent RPC readback",
  "confirmations": 5,
  "verificationChecks": [
    {
      "name": "transaction status",
      "passed": true,
      "expected": "success",
      "observed": "success"
    },
    {
      "name": "order terminal state",
      "passed": true,
      "expected": "FILLED",
      "observed": "FILLED"
    },
    {
      "name": "receiver unchanged from intent",
      "passed": true,
      "expected": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
      "observed": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088"
    },
    {
      "name": "executed exactly once",
      "passed": true,
      "expected": "1",
      "observed": "1"
    },
    {
      "name": "output asset is the registered asset",
      "passed": true,
      "expected": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
      "observed": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5"
    },
    {
      "name": "input actually spent",
      "passed": true,
      "expected": "> 0",
      "observed": "40000"
    },
    {
      "name": "spend within reservation",
      "passed": true,
      "expected": "<= 40000",
      "observed": "40000"
    },
    {
      "name": "output meets the user's minimum",
      "passed": true,
      "expected": ">= 0",
      "observed": "178247452766875"
    },
    {
      "name": "receiver balance increased by the reported output",
      "passed": true,
      "expected": ">= 178247452766875",
      "observed": "178247452766875"
    },
    {
      "name": "vault input decreased by exactly the reported spend",
      "passed": true,
      "expected": "40000",
      "observed": "40000"
    },
    {
      "name": "reservation fully settled",
      "passed": true,
      "expected": "closed, 0 remaining",
      "observed": "active=false remaining=0"
    }
  ],
  "finalOutcomeStatus": "VERIFIED_FILLED",
  "limitations": [
    "Market session was established from the xStocks issuer's published trading state and signed by the Bespeak operator. It is operator-attested, not oracle-verified. The signature proves which key asserted this state and when; it does not prove the state itself was correct."
  ],
  "receiptId": "0x78e041e7c48abb86543eec793de7608a6f79303e25f1e1293f0bd8c4c7221b8d"
} as unknown as StoredReceipt,
  "0xa91fc089b39fd8109ffe1db50a05b2b36927503cc73513812779957413931efb": {
  "receiptVersion": "1.0",
  "orderId": "0xb303f5a0697ff502e2e340bb741a7a1a46464a522d8b8fb6ff72775838f4d6ff",
  "occurrenceIndex": 0,
  "recurringId": null,
  "owner": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "vault": "0x225885C2eA154Ec53e5E8f768Ad6590Fb9dd13e5",
  "receiver": "0x1661A6D4D25123aFbbbBBCF3805ADd4c3161F088",
  "assetId": "0x6977a0680ac0652ec999cfcedf22b8c77022895b68a44c7a0e8854e30cbfdd44",
  "assetSymbol": "NVDAx",
  "assetRegistryRevisionAtCreation": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "assetRegistryRevisionAtExecution": "0xb24cd5d689eed6063b5c5339dc6235c69bb0d47fef11e7fea378099ef2c61368",
  "underlyingAddress": "0xc845b2894dBddd03858fd2D643B4eF725fE0849d",
  "wrapperAddress": "0xa8ddb5Cd96b5222AFe198316E9A57CAA642850D5",
  "wrapperVersion": 2,
  "deliveredInstrument": "wrapped",
  "inputToken": "0x4ae46a509F6b1D9056937BA4500cb143933D2dc8",
  "inputTokenSymbol": "USDG",
  "triggerType": "IMMEDIATE",
  "conditionIntent": "immediate",
  "conditionSource": "none (immediate)",
  "conditionSourceTier": "NONE",
  "conditionSourceVersion": "v2",
  "conditionObservationTimestamp": null,
  "conditionObservationHash": null,
  "conditionSourcePayloadHash": null,
  "marketStatus": "n/a",
  "corporateActionState": "none pending",
  "amountReserved": "400000",
  "actualInputSpent": "0",
  "unusedInputReleased": "0",
  "actualOutputReceived": "0",
  "minimumOutput": "1762294827595504",
  "quoteSource": "Uniswap v3 pool, quoted on chain via QuoterV2",
  "quoteTimestamp": "2026-09-26T00:13:42.000Z",
  "quoteHash": null,
  "routeSummary": "Uniswap v3 SwapRouter02 0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA, single pool",
  "routerAddress": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "approvalTarget": "0x4f0C28f5926AFDA16bf2506D5D9e57Ea190f9bcA",
  "executionPrice": null,
  "observedDifferenceBps": null,
  "executionRequestedAt": "2026-09-26T00:13:43.941Z",
  "transactionSubmittedAt": "2026-09-26T00:13:48.147Z",
  "transactionHash": "0x9f7f870a8a3549de385cbc7ab771284270589201f1807138e4501d2f03a65cad",
  "blockNumber": null,
  "blockHash": null,
  "verificationSource": "https://xlayerrpc.okx.com",
  "broadcastSource": "https://rpc.xlayer.tech",
  "firstVerificationAt": "2026-09-26T00:13:49.205Z",
  "finalVerificationAt": "2026-09-26T00:15:49.406Z",
  "verificationPolicy": "3 confirmations, independent RPC readback",
  "confirmations": 0,
  "verificationChecks": [
    {
      "name": "transaction included",
      "passed": false,
      "expected": "receipt present",
      "observed": "not found in window"
    }
  ],
  "finalOutcomeStatus": "VERIFICATION_TIMEOUT",
  "limitations": [
    "Market session was established from the xStocks issuer's published trading state and signed by the Bespeak operator. It is operator-attested, not oracle-verified. The signature proves which key asserted this state and when; it does not prove the state itself was correct."
  ],
  "receiptId": "0xa91fc089b39fd8109ffe1db50a05b2b36927503cc73513812779957413931efb"
} as unknown as StoredReceipt,
};
